GitStore/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using rrepo.Logic;
using rrepo.Models.Config;
using rrepo.Models.DataBase;
using rrepo.Models.DataForm;

namespace rrepo.Controllers
{
    public class AuthController : Controller
    {
        private async void Authenticate(AuthenticationDFM model)
        {
            var claims = new List<Claim>() {
                new Claim(ClaimsIdentity.DefaultNameClaimType, model.Login)
            };
            var id = new ClaimsIdentity(
                claims,
                "ApplicationCookie",
                ClaimsIdentity.DefaultNameClaimType,
                ClaimsIdentity.DefaultRoleClaimType
            );
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }

        [HttpGet]
        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
                return Redirect("/Home/Info?accName=" + User.Identity.Name);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login([FromServices] DataContext _context, AuthenticationDFM model)
        {
            if (User.Identity.IsAuthenticated)
                return Redirect("/Home/Info?accName=" + User.Identity.Name);
            if (_context.Accounts.FirstOrDefault(acc => (acc.Login == model.Login) && acc.Password.Equals(model.Password)) != null)
            {
                Authenticate(model);
                return Redirect("/Home/Index");
            }
            ViewData["isLoginError"] = "Неверный логин и(или) пароль";
            return View();
        }

        [HttpGet]
        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registration([FromServices] DataContext _context, RegistrationDFM model)
        {
            if (_context.Accounts.FirstOrDefault(user => user.Login == model.Login) != null)
            {
                ModelState.AddModelError("user_exists_error", "Пользователь с таким логином уже существует");
                return RedirectToAction("Registration");
            }
            _context.Accounts.Add(new AccountDBM() { Login = model.Login, EMail = model.EMail, Password = model.Password });
            _context.SaveChanges();
            var authModel = new AuthenticationDFM() { Login = model.Login, Password = model.Password };
            Authenticate(authModel);
            return Redirect("/Home/Index");
        }
        
        [HttpGet]
        public async Task<IActionResult> OAuth([FromServices] DataContext _context, string code, string access_token, string user_id)
        {
            if (access_token != null)
            {
                if (_context.Accounts.FirstOrDefault(user => user.OAuthToken == access_token) == null)
                {
                    _context.Accounts.Add(new AccountDBM() { Login = $"vk{user_id}", OAuthToken = access_token });
                    _context.SaveChanges();
                }
                var model = new AuthenticationDFM() { Login = $"vk{user_id}", Password = access_token };
                Authenticate(model);
                return Redirect("/Home/Index");
            }
            if (code == null)
                return RedirectToAction("Registration");
            else
                return Redirect($"https://oauth.vk.com/access_token?client_id=6797152&client_secret=MtzdiL0Ye7d5VmtInr5t&redirect_uri=https://gitstore.azurewebsites.net/Auth/OAuth&code={code}");
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }
    }
}

GitStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GitStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a asp-controller="Home" asp-action="Index" class="navbar-brand">GitStore</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse collapse" style="">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Search" class="nav-link @{ if (ViewData["Title"].Equals("Search")) { <text>active</text> } }">Поиск</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@User.Identity.Name</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a href="/Home/Info?accName=@User.Identity.Name" class="dropdown-item">Профиль</a>
                            <a asp-controller="Auth" asp-action="Logout" class="dropdown-item text-danger">Выход</a>
                        </div>
                    </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a asp-controller="Auth" asp-action="Login" class="nav-link @{ if (ViewData["Title"].Equals("Login")) { <text>active</text> } }">Вход</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Auth" asp-action="Registration" class="nav-link @{ if (ViewData["Title"].Equals("Registration")) { <text>active</text> } }">Регистрация</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content pt-5">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - GitStore</p>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>